# Generated by Django 4.1.5 on 2023-01-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=200)),
                ('attendees', models.IntegerField()),
            ],
        ),
    ]
