# Generated by Django 4.1.5 on 2023-01-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_WintR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='submission',
        ),
    ]
