# Generated by Django 4.1.5 on 2023-01-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_WintR', '0005_submission_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='attendees',
            new_name='impressions',
        ),
    ]
