# Generated by Django 4.1.5 on 2023-01-29 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_WintR', '0007_rename_eventid_submission_submissionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attendees',
            field=models.ManyToManyField(related_name='attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
